name: wechat_kit_example
description: Demonstrates how to use the wechat_kit plugin.
publish_to: 'none'
version: 1.0.0+100

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  wechat_kit:
    # When depending on this package from a real application you should use:
    #   wechat_kit: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version. 
    path: ../
  wechat_kit_extension: ^1.0.0

  image: ^3.0.1
  flutter_cache_manager: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
