kind: pipeline
name: default

steps:
- name: prepare
  image: v7lin/flutter:1.2.1-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages get

- name: analyze
  image: v7lin/flutter:1.2.1-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter analyze

- name: test
  image: v7lin/flutter:1.2.1-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter test
  - pushd example/
  - flutter test

- name: publish-check
  image: v7lin/flutter:1.2.1-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages pub publish --dry-run

volumes:
- name: pub-cache
  temp: {}
